import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { submitSuspensionReview } from "./actions";
export default async function SuspensionReviewPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login?next=/account/suspension-review");
  const { data: profile } = await supabase.from("profiles").select("account_status, suspension_reason, phone").eq("id", user.id).single();
  const { data: requests } = await supabase.from("suspension_review_requests").select("id,status,created_at,admin_note").eq("user_id", user.id).order("created_at", { ascending:false });
  return <main className="min-h-screen bg-[#061116] px-4 py-10 text-white"><div className="mx-auto max-w-3xl rounded-[2rem] border border-white/10 bg-white/5 p-6 md:p-8"><p className="text-xs font-bold uppercase tracking-[0.28em] text-emerald-400">Account Review</p><h1 className="mt-3 text-3xl font-black">Request Suspension Review</h1><p className="mt-3 text-slate-300">Account status: <strong>{profile?.account_status || "active"}</strong>. {profile?.suspension_reason && `Reason: ${profile.suspension_reason}`}</p>{profile?.account_status === "active" ? <p className="mt-6 rounded-2xl bg-emerald-500/10 p-4 text-emerald-200">Your account is active.</p> : <form action={submitSuspensionReview} className="mt-6 space-y-4"><textarea name="explanation" required rows={5} placeholder="Explain why your account should be reviewed" className="w-full rounded-2xl border border-white/10 bg-white/10 p-4"/><input name="contact_phone" defaultValue={profile?.phone || ""} placeholder="Contact phone (optional)" className="w-full rounded-2xl border border-white/10 bg-white/10 p-4"/><textarea name="supporting_note" rows={3} placeholder="Supporting note (optional)" className="w-full rounded-2xl border border-white/10 bg-white/10 p-4"/><button className="w-full rounded-full bg-emerald-500 px-6 py-4 font-bold text-[#04130c]">Submit Review Request</button></form>}<div className="mt-8 grid gap-3">{(requests || []).map((request) => <div key={request.id} className="rounded-2xl border border-white/10 bg-white/5 p-4"><strong className="uppercase text-emerald-300">{request.status}</strong><p className="mt-1 text-sm text-slate-400">{new Date(request.created_at).toLocaleString()}</p>{request.admin_note && <p className="mt-2">{request.admin_note}</p>}</div>)}</div></div></main>;
}
